# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				arrow = true
				cow = true
				pig = true
				skeleton = true
				llama = true
				bat = true
				husk = true
				rabbit = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				salmon = true
				goat = true
				furnace_minecart = true
				horse = true
				phantom = true
				minecart = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				donkey = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				blaze = true
				cat = true
				zombie = true
				sheep = true
				fireball = true
				player = true
				pufferfish = true
				potion = true
				wolf = true
				villager = true
				tnt_minecart = true
				zombie_villager = true
				small_fireball = true
				cave_spider = true
				cod = true
				witch = true
				spider = true

			[light_sources.settings.entities.bewitchment]
				werewolf = true
				raven = true
				owl = true
				herne = true
				snake = true
				toad = true
				lilith = true
				leonard = true
				ghost = true
				vampire = true
				baphomet = true
				hellhound = true
				demon = true

			[light_sources.settings.entities.campanion]
				lawn_chair = true
				diamond_spear = true
				netherite_spear = true
				grappling_hook = true

			[light_sources.settings.entities.additionaladditions]
				glow_stick = true

			[light_sources.settings.entities.another_furniture]
				seat = true

			[light_sources.settings.entities.halfdoors]
				tiny_door = true
				door_saw = true

			[light_sources.settings.entities.bwplus]
				leshon = true

			[light_sources.settings.entities.mannequins]
				mannequin = true
				statue = true

			[light_sources.settings.entities.the_aether]
				white_swet = true
				cockatrice = true
				golden_dart = true
				purple_swet = true
				golden_swet = true
				aerbunny = true
				aerwhale = true
				aechor_plant = true
				blue_swet = true
				moa = true

			[light_sources.settings.entities.arcanus]
				magic_missile = true

			[light_sources.settings.entities.create]
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.twilightforest]
				wand_bolt = true
				loyal_zombie = true

			[light_sources.settings.entities.neutrino]
				rat = true
				duck = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.gateofbabylon]
				yoyo = true

